### ISSUE TITLE
Doesn't work for eBay.de

### ISSUE THREAD

**Issue by realinstinct** [eladnava/ebay-popularity-sort#10]
Hello, 
firstly thank you for this extension, this helps me alot for ebay.com marketplace. But I want to research on ebay.de but it doesn't work. I see the text, that the results are modified by eBay™ Popularity Sort but it doesn't show, how many products are sold. 
What can I do, to make this work for eBay.de ?

**Comment by eladnava** [comment]
Hi @realinstinct,
It appears that ebay.de does not display the number of times an item has been sold in the search results:
https://www.ebay.de/sch/i.html?_odkw=bulb&_osacat=0&_from=R40&_trksid=p2045573.m570.l1313.TR11.TRC1.A0.H0.Xdji+mavic.TRS0&_nkw=dji+mavic&_sacat=0

Therefore, this extension cannot work on ebay.de. Use ebay.com instead if possible. 👍
