### ISSUE TITLE
issue in the extension

### ISSUE THREAD

**Issue by bammou** [eladnava/ebay-popularity-sort#11]
hi, i'm an ebay dropshipper and i use this extension very often in my product researsh. first of all i wanna thank you very much for this usefull extension, it helps me a lot and save me money and time. 
i want to inform you that there is a problem with it. it s been 3 days that the extension doesn't work, i've tried it on chrome and firefox and i find the same problem, the item's order stay the same even though the extension is activated. please tell me if it is just my case or there is actually a problem. thaankks

**Comment by eladnava** [comment]
Thanks for reporting! This has occurred due to a chance in CSS class declarations in the eBay website.

Now resolved in `1.0.6`, please update in Chrome Store:
https://chrome.google.com/webstore/detail/gikmaepdichkplhdildclnphgpiaiibf

**Comment by bammou** [comment]
thank you for the help, the problem is solved in chrome but not yet in firefox. hope it will be solved. thaaanks agaiin!!
