### ISSUE TITLE
extension does not work in firefox

### ISSUE THREAD

**Issue by bammou** [eladnava/ebay-popularity-sort#12]
hi, the extension still don't work in firefox even though it work on chrome. can you please solve it? thaanks

**Comment by eladnava** [comment]
@bammou How are you using Chrome extensions on Firefox?

eBay Popularity Sort is a Chrome-only extension.

**Comment by bammou** [comment]
https://addons.mozilla.org/fr/firefox/addon/ebay-popularity-sorter/

**Comment by eladnava** [comment]
Sorry but that's a different plugin by a different author. It is not supported by me. This plugin is Chrome only.

**Comment by bammou** [comment]
Sorry i thought it was yours, anyway thank you veryy much for your work, i
appreciate it.
