### ISSUE TITLE
Extension no longer works on Brave

### ISSUE THREAD

**Issue by dooglio** [eladnava/ebay-popularity-sort#13]
I'm running on Brave browser with Shields Up turned off. I've been using this extension for years without any problems, but then recently it stopped working out of the blue. My guess is that eBay changed something in their HTML layout which is breaking the extension.

Here are screenshots below:

This is with the extension turned off:
![image](https://github.com/eladnava/ebay-popularity-sort/assets/643129/edb9067a-dc16-4085-864d-743979dd4791)

Here it is with the extension turned on and page reloaded:
![image](https://github.com/eladnava/ebay-popularity-sort/assets/643129/bb7bd6d4-f011-46af-8288-c61ef7b25522)

**Comment by eladnava** [comment]
Hi @dooglio,
Thanks for reporting this!

Indeed, eBay changed its CSS class name for the hotness text (number of times an item was sold) and this messed up the sort order.

However, it appears you are trying to use the extension to sort a certain seller's product list, yet the extension is only meant to sort the [general search results](https://www.ebay.com/sch/i.html?LH_BIN=1&_from=R40&_sacat=0&_sop=12&_nkw=edison+bulb&rt=nc&_ipg=240).

In any case, I've fixed the issue in commit https://github.com/eladnava/ebay-popularity-sort/commit/f77d22fb0346f2ec354189888c1d08b7bdb083d2 and published version `1.0.8` to the Chrome Web Store for review. It will most likely take a few days before Google approves the release.

Thanks again for your help with this!

**Comment by dooglio** [comment]
Just to let you know, 1.0.8 is available on Chrome Web Store and it works just like before. Thanks for the fix!

**Comment by eladnava** [comment]
Hi @dooglio,
Glad to hear! 🎉  You're very welcome.
