### ISSUE TITLE
Works on .com/.co.uk, no effect on .ie

### ISSUE THREAD

**Issue by ppriest** [eladnava/ebay-popularity-sort#5]
Guess it has a hard-coded list of domains?

**Comment by ppriest** [comment]
(or .de, .fr, .com.au etc. )

**Comment by eladnava** [comment]
Thanks for the report @ppriest, this has been fixed in https://github.com/eladnava/ebay-popularity-sort/commit/e212739fd6b7532e1f846e89b8023566f2015d4d.
