### ISSUE TITLE
Mixing of "% off" and "sold"

### ISSUE THREAD

**Issue by daBrado** [eladnava/ebay-popularity-sort#7]
The sort seems to be interpreting the number for "% off" as the number for "sold"; e.g. a "40% off" with no "sold" report will appear between a "41 sold" and "37 solds" (as in the screenshot).

![2017-10-08-170719_923x665_scrot](https://user-images.githubusercontent.com/383026/31322391-b1fad5d8-ac4b-11e7-8f64-7902eb607e98.png)

**Comment by eladnava** [comment]
Hi @daBrado,
Thanks so much for your help in reporting this issue!

It has now been resolved via https://github.com/eladnava/ebay-popularity-sort/commit/ccad30a8dbc9f8a3bcf3e182c570443b541a909f and published to the Chrome Web Store as `1.0.2`.

**Comment by daBrado** [comment]
Awesome, thank you!
