### ISSUE TITLE
Higher number not showing

### ISSUE THREAD

**Issue by jaykeny** [eladnava/ebay-popularity-sort#8]
I see those with 900 sold, but there are some that have 1000, 2000, and more that do not show on the first page

**Comment by eladnava** [comment]
Hi @IFeelYourPain,
I, unfortunately, do not feel your pain. 🤣 

A search for Sandisk Cruzer returns the following:
![screen shot 2018-02-08 at 8 58 36 am](https://user-images.githubusercontent.com/4394189/35946115-475f5532-0cae-11e8-9e36-bc29bad15cf9.png)

There are items sold for over 10k times.

Try setting Items Per Page to 200 (at the bottom of the search results page).

**Comment by mazh-dini** [comment]
I am also not able to use the extension, I was at first and it was extremely useful but now I can't. I think maybe it has to do with a chrome update possibly? Also alot of people are having trouble as well saying the same thing as I am on the extension page. Can you please take a look at it when you can. I would love too and I have but my programming skills are poor

**Comment by eladnava** [comment]
@mazh-dini Thanks for bringing this to my attention. eBay has changed their HTML format. The extension has been patched and published to the Chrome Web Store.

**Comment by eladnava** [comment]
Closing this for now, please reopen if this issue persists.
