### ISSUE TITLE
Recent update shows results from previous searchs

### ISSUE THREAD

**Issue by mazh-dini** [eladnava/ebay-popularity-sort#9]
The recent update has fixed the issues with it not working at times, however whenever I search for a second item, the results for the previous items are displayed.

**Comment by eladnava** [comment]
Hi @mazh-dini,
Unfortunately I can't reproduce.

I searched for the following on eBay:
https://www.ebay.com/sch/i.html?_odkw=usb+cable+5m&_osacat=0&_from=R40&_trksid=p2045573.m570.l1313.TR0.TRC0.H0.Xusb+cable.TRS0&_nkw=usb+cable&_sacat=0

Then, I clicked the search input and added " 5m" to the term and clicked enter. The page reloaded and the results were different than the previous page.

Do you have any reproduction steps?

**Comment by mazh-dini** [comment]
Yea it works when I use the link you provided. But when it's on ebay.com.**au** items from previous searchs will show up.
![untitled](https://user-images.githubusercontent.com/18192025/40535738-550f4adc-604d-11e8-9a49-b706a0d0cdc0.png)
![untitled1](https://user-images.githubusercontent.com/18192025/40535740-5542112e-604d-11e8-921c-c17448901747.png)
Clearing cookies appears to stop it but continuing to use ebay will result in the same thing happening to other items

**Comment by eladnava** [comment]
Can't seem to reproduce on ebay.com.au either:

https://www.ebay.com.au/sch/i.html?_from=R40&_trksid=p2334524.m570.l1313.TR12.TRC2.A0.H0.Xscreen+protector.TRS0&_nkw=screen+protector&_sacat=0&LH_TitleDesc=0&_osacat=0&_odkw=usb+cable

Searched for "screen protector" and then changed the search to "usb cable" and the results were accurate. Do you have a link to reproduce this?

**Comment by nixsoh** [comment]
Hi I have the same problem. I'm using mac. My previous searches appear on top of the results instead.

**Comment by artwebUK** [comment]
Hi, same problem here. Mixed items from all previous searches filtered by total sales.

**Comment by artwebUK** [comment]
Right... it's looks like all listings that you clicked on to appearing on the next search term results.

For example if you searched for "usb cable" and clicked on two listings, then searched say for "screen protectors", you will see both usb cables results from previous search.

**Comment by eladnava** [comment]
Excellent, I was able to reproduce! 🎉

This was due to a loose regular expression that was matching the recently viewed items column in the search sidebar.  

Published the fix to the Chrome Web Store!
